name: Toolkit-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - conda>=4.5.10
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - gdal
  - scikit-image
  - pyshp
  - fiona
  - shapely
  - krb5
  - pip:
    - git+https://github.com/geoscixyz/Toolkit.git@deploy_binder
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - nbstripout
    - numpydoc
